# contikipy config
path:    /home/mike/Repos/contiki-usdn
wd:      /examples/ipv6/sdn-udp
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results
csc:     usdn-20-node.csc
target:  exp5438

# log parser config
stats:
  run:                  False
  st_rdc_hops:          1  # Radio duty cycle vs hops
  st_prr_hops:          1  # Packet receive ratio vs hops
  st_lat_hops_lat_mean: 1  # Hops vs mean latency
  st_lat_hops_lat_e2e:  1  # Hops vs end-to-end latency

sdn_stats:
  run:                  False
  st_sdn_join:          1  # SDN controller join timer
  st_sdn_traffic_ratio: 1  # Traffic ratio of all traffic (incl sdn)

multi_sim_analysis:
  run:                  False
  cmp_tr_br:            1  # Compare traffic ratio over bit rates

scenarios:
  run:                  True
  st_flow_lat:          1  # Flow vs latency


# simulation config
simulations:
    - desc:           2_FLOW_REROUTE_RPL
      csc:            usdn-reroute.csc
      makeargs:
        MAC:          CONTIKIMAC
        SDN:          0
        NUM_APPS:     2
        APPID:        [0,1]
        TXNODE:       [2,3]
        RXNODE:       [1,1]
        BRMIN:        [1,20]
        BRMAX:        [5,20]
        REROUTE:      1

    # - desc:           2_FLOW_REROUTE_SDN
    #   csc:            usdn-reroute.csc
    #   makeargs:
    #     MAC:          CONTIKIMAC
    #     SDN:          1
    #     NUM_APPS:     2
    #     APPID:        [0,1]
    #     TXNODE:       [2,3]
    #     RXNODE:       [1,1]
    #     BRMIN:        [1,20]
    #     BRMAX:        [5,20]
    #     REROUTE:      1

  # - desc:           RPL_APP
  #   makeargs:
  #     SDN:          0
  #     NUM_APPS:     1
  #     APPID:        [1]
  #     TXNODE:       0
  #     RXNODE:       1
  #     BRMIN:        [60]
  #     BRMAX:        [75]
  #
  # - desc:           SDN_APP
  #   makeargs:
  #     SDN:          1
  #     NUM_APPS:     1
  #     APPID:        [1]
  #     TXNODE:       0
  #     RXNODE:       1
  #     BRMIN:        [60]
  #     BRMAX:        [75]
  # - desc:           REROUTE_RPL_INTERF
  #   csc:            usdn-reroute.csc
  #   makeargs:
  #     MAC:          CONTIKIMAC
  #     SDN:          0
  #     NUM_APPS:     3
  #     APPID:        [0,1,2]
  #     TXNODE:       [2,7,3]
  #     RXNODE:       [1,1,1]
  #     BRMIN:        [5,5,20]
  #     BRMAX:        [6,6,20]
  #     REROUTE:      1
  #
  # - desc:           REROUTE_SDN_INTERF
  #   csc:            usdn-reroute.csc
  #   makeargs:
  #     MAC:          CONTIKIMAC
  #     SDN:          1
  #     NUM_APPS:     3
  #     APPID:        [0,1,2]
  #     TXNODE:       [2,7,3]
  #     RXNODE:       [1,1,1]
  #     BRMIN:        [5,5,20]
  #     BRMAX:        [6,6,20]
  #     REROUTE:      1

multiflow:
  - FLOWID:         1
    TXNODE:         3
    RXNODE:         1
    BRMIN:          0.23
    BRMAX:          0.23
  - FLOWID:         2
    TXNODE:         3
    RXNODE:         1
    BRMIN:          10
    BRMAX:          10
