contiki: /home/mike/Repos/contiki-usdn
wd:      /examples/ipv6/sdn
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results
csc:     usdn-30-node.csc

stats:
  run:                  True
  st_rdc_hops:          1  # Radio duty cycle vs hops
  st_prr_hops:          1  # Packet receive ratio vs hops
  st_lat_hops_lat_mean: 1  # Hops vs mean latency
  st_lat_hops_lat_e2e:  1  # Hops vs end-to-end latency

sdn_stats:
  run:                  True
  st_sdn_join:          1  # SDN controller join timer
  st_sdn_traffic_ratio: 1  # Traffic ratio of all traffic (incl sdn)

sdn_scenarios:
  run:                  True
  sc_sdn_rr:            1  # SDN re-routing scenario

multi_sim_analysis:
  run:                  False
  cmp_tr_br:            1  # Compare traffic ratio over bit rates
