# ----------------------------------------------------------------------------
# ContikiPy
# ----------------------------------------------------------------------------

path:    /home/mike/Repos/usdn
wd:      /examples/ipv6/sdn-udp
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results/20_NODE_RETRY
csc:     usdn-30-node.csc
target:  exp5438

# ----------------------------------------------------------------------------
# Results Options
# packet regex ... https://regex101.com/r/mE5wK0/1
# ----------------------------------------------------------------------------
logtypes:
  - type:    cooja
    fmt_re:  '^\s*(?P<time>\d+):\s*(?P<id>\d+):'
    log_re:  \s*\[(?P<level>STAT):\s*(?P<module>[\w,-]+)\s*]\s*

data:
  config:     [pow, app, sdn, node, icmp, join]
  dictionary:
    - type:   pow
      regex:  .*P \d+.\d+ (?P<seqid>\d+).*\(radio (?P<all_radio>\d+\W{1,2}\d+).*(?P<radio>\d+\W{1,2}\d+).*(?P<all_tx>\d+\W{1,2}\d+).*(?P<tx>\d+\W{1,2}\d+).*(?P<all_listen>\d+\W{1,2}\d+).*(?P<listen>\d+\W{1,2}\d+)
    - type:   app
      regex:  (?P<status>(TX|RX))\s+(?P<typ>\S+)(?:\s+s:(?P<src>\d+)|\s+d:(?P<dest>\d+)|\s+a:(?P<app>\d+)|\s+id:(?P<seq>\d+)|\s+h:(?P<hops>[1-5])|\s+m:(?P<mac>\d+))+.*?$
    - type:   sdn
      regex:  (?P<status>(OUT|BUF|IN))\s+(?P<typ>\S+)(?:\s+s:(?P<src>\d+)|\s+d:(?P<dest>\d+)|\s+a:(?P<app>\d+)|\s+id:(?P<seq>\d+)|\s+h:(?P<hops>[1-5])|\s+m:(?P<mac>\d+))+.*?$
    - type:   node
      regex:  h:(?P<rank>\d+), n:(?P<degree>\d+)
    - type:   icmp
      regex:  (?:\s+type:(?P<type>\d+)|\s+code:(?P<code>\d+))+.*?$
    - type:   join
      regex:  (?:\s+n:(?P<node>\d+)|\s+c:(?P<controller>\d+)|\s+dag:(?P<dag>\d+)|\s+dao:(?P<dao>\d+))+.*?$

# ----------------------------------------------------------------------------
# Multiflow
# ----------------------------------------------------------------------------
multiflow:
  - id:               1_flow
    NUM_APPS:         1
    flows:
      FLOWIDS:        1
      TXNODES:        0
      RXNODES:        1
      DELAY:          240
      BRMIN:          60
      BRMAX:          75

  - id:               1_flow_p2p
    NUM_APPS:         1
    flows:
      FLOWIDS:        1
      TXNODES:        [18,19]
      RXNODES:        [20,21]
      DELAY:          [60,60]
      BRMIN:          [60,60]
      BRMAX:          [75,75]

  - id:               2_flow_rr
    NUM_APPS:         2
    flows:
      FLOWIDS:        [1,2]
      TXNODES:        [3,3]
      RXNODES:        [1,1]
      DELAY:          [120,120]
      BRMIN:          [0.23,10]
      BRMAX:          [0.23,10]

# ----------------------------------------------------------------------------
# Simulations
# ----------------------------------------------------------------------------
simulations:
# # ----------------------------------------------------------------------------
  # - desc:           RPL
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          0
  #   multiflow:      1_flow
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_traffic_ratio   # SDN traffic ratio
  - desc:           SDN
    makeargs:
      MAC:          CSMA
      SDN:          1
      FTREFRESH:    1
      FTSRETRY:     0
      FORCENSU:     1
      NSUFREQ:      180  # NSU frequency actually helps over 0 frequency
    multiflow:      1_flow
    plot:
      - hops_rdc            # Radio duty cycle vs hops
      - hops_prr            # Packet receive ratio vs hops
      - hops_lat_mean       # Hops vs mean latency
      - hops_lat_e2e        # Hops vs end-to-end latency
      - sdn_join            # SDN controller join time
      - sdn_traffic_ratio   # SDN traffic ratio

# ----------------------------------------------------------------------------
  # - desc:           SDN-NSU-10
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          1
  #     FTREFRESH:    1
  #     FORCENSU:     1
  #     NSUFREQ:      10  # NSU frequency actually helps over 0 frequency
  #   multiflow:      1_flow
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio
  #
  # - desc:           SDN-NSU-30
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          1
  #     FTREFRESH:    1
  #     FORCENSU:     1
  #     NSUFREQ:      30  # NSU frequency actually helps over 0 frequency
  #   multiflow:      1_flow
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio
  #
  # - desc:           SDN-NSU-60
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          1
  #     FTREFRESH:    1
  #     FORCENSU:     1
  #     NSUFREQ:      60  # NSU frequency actually helps over 0 frequency
  #   multiflow:      1_flow
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio

# ----------------------------------------------------------------------------
  # - desc:           SDN-FT-10
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          1
  #     FTREFRESH:    1
  #     FORCENSU:     1
  #     NSUFREQ:      300  # NSU frequency actually helps over 0 frequency
  #     FTSFREQ:      60
  #   multiflow:      1_flow
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio
  #
  # - desc:           SDN-FT-60
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          1
  #     FTREFRESH:    1
  #     FORCENSU:     1
  #     NSUFREQ:      300  # NSU frequency actually helps over 0 frequency
  #     FTSFREQ:      180
  #   multiflow:      1_flow
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio
  #
  # - desc:           SDN-FT-600
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          1
  #     FTREFRESH:    1
  #     FORCENSU:     1
  #     NSUFREQ:      300  # NSU frequency actually helps over 0 frequency
  #     FTSFREQ:      300
  #   multiflow:      1_flow
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio

# ----------------------------------------------------------------------------
# analysis (comparison) config
# ----------------------------------------------------------------------------
analysis:
# ----------------------------------------------------------------------------
  - sims:
    - SDN
    - RPL
    plots:
      - hops_rdc
      - hops_prr
      - hops_lat_mean
      - hops_lat_e2e
      - join

# ----------------------------------------------------------------------------
  # - sims:
  #   -  SDN-NSU-10
  #   -  SDN-NSU-30
  #   -  SDN-NSU-60
  #   plots:
  #   - hops_lat_e2e

# ----------------------------------------------------------------------------
  # - sims:
  #   -  SDN-FT-10
  #   -  SDN-FT-60
  #   -  SDN-FT-600
  #   plots:
  #   - hops_lat_e2e
