# ----------------------------------------------------------------------------
# ContikiPy
# ----------------------------------------------------------------------------
contiki: /home/mike/Repos/atomic
wd:      /home/mike/Repos/atomic/examples/atomic
fmt:     cooja
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results/ATOMIC_100
csc:     atomic-30-node.csc
target:  sky

# ----------------------------------------------------------------------------
# Results Options
# packet regex ... https://regex101.com/r/26KZoD/15/
# ----------------------------------------------------------------------------
logtypes:
  - type:    cooja
    fmt_re:  '^\s*(?P<time>\d+):\s+(?P<id>\d+):'

formatters:
  dictionary:
    # atomic
    - type:  atomic-energy
      regex: \s+(?P<level>[\w,-]+):\s+(?P<module>\w+)\s*ep:(?P<epoch>\d+)\s+(?P<op_type>\w+)(?:\s*h:(?P<hops>\d+)|\s+np:(?P<n_phases>\d+)|\s+gon:(?P<gon>\d+)|\s+ron:(?P<ron>\d+)|\s+con:(?P<con>\d+)\s+\(r (?P<all_rdc>\d+\W{1,2}\d+)| \/ (?P<rdc>\d+\W{1,2}\d+))+.*?$
    - type:  atomic-op
      regex: \s+(?P<level>[\w,-]+):\s+(?P<module>\w+)\s*ep:(?P<epoch>\d+)\s+(?P<op_type>\w+)(?:\s*h:(?P<hops>\d+)|\scp:\s*(?P<c_phase>\d+)|\s+tp:\s*(?P<n_phases>\d+)|\s+dur:\s*(?P<c_time>\d+)|\s+tdur:\s*(?P<op_duration>\d+)|\s+an:(?P<active>\d+))+.*?$

# ----------------------------------------------------------------------------
# Simulations
# ----------------------------------------------------------------------------
simulations:
  # 100 Node Atomic
  - desc:           Atomic_100
    type:           atomic
    contiki:        /home/mike/Repos/atomic
    wd:             /home/mike/Repos/atomic/examples/atomic
    csc:            atomic-100-node.csc
    makeargs:
      ATM_CONF_MAX_NODES:         100
      ATM_CONF_COLLECT_ALL_NODES: 1
      ATM_CONF_REACT_ALL_NODES:   1
      ATM_CONF_OP_FREQ:           60
    regex:
      - 'atomic-energy'
      - 'atomic-op'
    plot:
      - atomic_op_times
      - atomic-energy-vs-hops

# ----------------------------------------------------------------------------
# compare (comparison) config
# ----------------------------------------------------------------------------
compare:
  - sims:
    # which sims do we want to compare?
    - Atomic_100
    # which plots do we want to compare?
    plots:
      - atomic_energy_v_hops
      - atomic_op_times
