# ----------------------------------------------------------------------------
# ContikiPy
# ----------------------------------------------------------------------------

path:    /home/mike/Repos/usdn
wd:      /examples/ipv6/sdn-udp
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results
csc:     usdn-20-node.csc
target:  exp5438

# ----------------------------------------------------------------------------
# Multiflow
# ----------------------------------------------------------------------------

multiflow:
  - id:               1_flow
    NUM_APPS:         1
    flows:
      FLOWIDS:        1
      TXNODES:        0
      RXNODES:        1
      DELAY:          120
      BRMIN:          60
      BRMAX:          75

  - id:               2_flow_rr
    NUM_APPS:         2
    flows:
      FLOWIDS:        [1,2]
      TXNODES:        [3,3]
      RXNODES:        [1,1]
      DELAY:          [120,120]
      BRMIN:          [0.23,10]
      BRMAX:          [0.23,10]

# ----------------------------------------------------------------------------
# Simulations
# ----------------------------------------------------------------------------
simulations:
# ----------------------------------------------------------------------------
  # - desc:           RPL-Scenario
  #   csc:            usdn-reroute.csc
  #   makeargs:
  #     MAC:          CONTIKIMAC
  #     SDN:          0
  #     REROUTE:      0
  #   multiflow:      2_flow_rr
  #   plot:
  #     - flow_lat            # Flow vs latency
  #
  # - desc:           SDN-Scenario
  #   csc:            usdn-reroute.csc
  #   makeargs:
  #     MAC:          CONTIKIMAC
  #     SDN:          1
  #     REROUTE:      1
  #     FTSRETRY:     0
  #     NSUFREQ:      60
  #   multiflow:      2_flow_rr
  #   plot:
  #     - flow_lat            # Flow vs latency

# ----------------------------------------------------------------------------
  # - desc:           RPL
  #   makeargs:
  #     MAC:          CSMA
  #     SDN:          0
  #   multiflow:      1_flow
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_traffic_ratio   # SDN traffic ratio
  - desc:           SDN
    makeargs:
      MAC:          CSMA
      SDN:          1
      FTREFRESH:    1
      FORCENSU:     1
      NSUFREQ:      600
    multiflow:      1_flow
    plot:
      - hops_rdc            # Radio duty cycle vs hops
      - hops_prr            # Packet receive ratio vs hops
      - hops_lat_mean       # Hops vs mean latency
      - hops_lat_e2e        # Hops vs end-to-end latency
      - sdn_join            # SDN controller join time
      - sdn_traffic_ratio   # SDN traffic ratio

# ----------------------------------------------------------------------------
# analysis (comparison) config
# ----------------------------------------------------------------------------
analysis:
# ----------------------------------------------------------------------------
  - sims:
    - SDN
    - RPL
    plots:
      - hops_rdc
      - hops_prr
      - hops_lat_mean
      - hops_lat_e2e
      - join
# ----------------------------------------------------------------------------
  # - sims:
  #   - SDN
  #   plots:
  #   - join
# ----------------------------------------------------------------------------
  # - sims:
  #   - SDN-Scenario
  #   - RPL-Scenario
  #   plots:
  #     - flow_lat
