# ----------------------------------------------------------------------------
# ContikiPy
# ----------------------------------------------------------------------------
path:    /home/mike/Repos/atomic
wd:      /examples/atomic
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results/ATOMIC
csc:     atomic-30-node.csc
target:  sky

# ----------------------------------------------------------------------------
# Results Options
# packet regex ... https://regex101.com/r/0ihQFC/1
# ----------------------------------------------------------------------------
logtypes:
  - type:    cooja
    fmt_re:  ^\s*(?P<time>\d+):\s+(?P<id>\d+):\s+
    log_re:  (?P<level>[\w,-]+):\s+(?P<module>\w+)\s*ep:(?P<epoch>\d+)\s+(?P<op_type>\w+)

data:
  config:     [pow]
  dictionary:
    - type:   pow
      regex:  (?:\s*h:(?P<type>\d+)|\s+np:(?P<n_phases>\d+)|\s+gon:(?P<gon>\d+)|\s+ron:(?P<ron>\d+)|\s+con:(?P<con>\d+)\s+\(r (?P<all_rdc>\d+\W{1,2}\d+)| \/ (?P<rdc>\d+\W{1,2}\d+))+.*?$
# ----------------------------------------------------------------------------
# Simulations
# ----------------------------------------------------------------------------
simulations:
# ----------------------------------------------------------------------------
  - desc:             ATM
    makeargs:
      SDN:  0
    plot:
      - associate_time
      - collect_time
      - configure_time
      - react_time
