# ----------------------------------------------------------------------------
# ContikiPy
# ----------------------------------------------------------------------------
contiki: /home/mike/Repos/atomic
wd:      /home/mike/Repos/atomic/examples/atomic
fmt:     cooja
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results/ATOMIC
csc:     atomic-30-node.csc
target:  sky

# ----------------------------------------------------------------------------
# Results Options
# packet regex ... https://regex101.com/r/26KZoD/15/
# ----------------------------------------------------------------------------
logtypes:
  - type:    cooja
    fmt_re:  '^\s*(?P<time>\d+):\s+(?P<id>\d+):'

formatters:
  dictionary:
    # atomic
    - type:  atomic-energy
      regex: \s+(?P<level>[\w,-]+):\s+(?P<module>\w+)\s*ep:(?P<epoch>\d+)\s+(?P<op_type>\w+)(?:\s*h:(?P<hops>\d+)|\s+np:(?P<n_phases>\d+)|\s+gon:(?P<gon>\d+)|\s+ron:(?P<ron>\d+)|\s+con:(?P<con>\d+)\s+\(r (?P<all_rdc>\d+\W{1,2}\d+)| \/ (?P<rdc>\d+\W{1,2}\d+))+.*?$
    - type:  atomic-op
      regex: \s+(?P<level>[\w,-]+):\s+(?P<module>\w+)\s*ep:(?P<epoch>\d+)\s+(?P<op_type>\w+)(?:\s*h:(?P<hops>\d+)|\scp:\s*(?P<c_phase>\d+)|\s+tp:\s*(?P<n_phases>\d+)|\s+dur:\s*(?P<c_time>\d+)|\s+tdur:\s*(?P<op_duration>\d+)|\s+an:(?P<active>\d+))+.*?$

# ----------------------------------------------------------------------------
# Simulations
# ----------------------------------------------------------------------------
simulations:
  # 40 Node
  - desc:     ATM_20
    type:     atomic
    contiki:  /home/mike/Repos/atomic
    wd:       /home/mike/Repos/atomic/examples/atomic
    csc:      atomic-20-node.csc
    makeargs:
      ATM_CONF_MAX_NODES:         20
      ATM_CONF_COLLECT_ALL_NODES: 1
      ATM_CONF_REACT_ALL_NODES:   1
      ATM_CONF_OP_FREQ:           60
      # ATM_CONF_COLLECT_FREQ:      3
      # ATM_CONF_REACT_FREQ:        5
      # ATM_CONF_CONFIGURE_FREQ:    7
    plot:
      - atomic_energy_v_hops
      - atomic_op_times

# ----------------------------------------------------------------------------
# compare (comparison) config
# ----------------------------------------------------------------------------
compare:
  - sims:
    # which sims do we want to compare?
    - ATM_20
    # which plots do we want to compare?
    plots:
      - atomic_energy_v_hops
      - atomic_op_times
