# contikipy config
path:    /home/mike/Repos/contiki-usdn
wd:      /examples/ipv6/sdn-udp
log:     /tools/cooja/build/COOJA.testlog
out:     /home/mike/Results
csc:     usdn-20-node.csc
target:  exp5438

# multiflow config
multiflow:
  1_flow:
    - FLOWID:         1
      TXNODES:        0
      RXNODES:        1
      BRMIN:          60
      BRMAX:          75
  2_flow:
    - FLOWID:         1
      TXNODES:        3
      RXNODES:        1
      BRMIN:          0.23
      BRMAX:          0.23
    - FLOWID:         2
      TXNODES:        3
      RXNODES:        1
      BRMIN:          10
      BRMAX:          10

# simulation config
simulations:
  # - desc:           RPL-Scenario
  #   csc:            usdn-reroute.csc
  #   makeargs:
  #     MAC:          CONTIKIMAC
  #     SDN:          0
  #     NUM_APPS:     2
  #     APPID:        [0,1]
  #     TXNODES:      [2,3]
  #     RXNODES:      [1,1]
  #     BRMIN:        [1,20]
  #     BRMAX:        [5,20]
  #     REROUTE:      0
  #     FTSRETRY:     0
  #     NSUFREQ:      0
  #   plot:
  #     - flow_lat            # Flow vs latency
  #
  # - desc:           SDN-Scenario
  #   csc:            usdn-reroute.csc
  #   makeargs:
  #     MAC:          CONTIKIMAC
  #     SDN:          1
  #     NUM_APPS:     2
  #     APPID:        [0,1]
  #     TXNODES:      [2,3]
  #     RXNODES:      [1,1]
  #     BRMIN:        [1,20]
  #     BRMAX:        [5,20]
  #     REROUTE:      0
  #     FTSRETRY:     0
  #     NSUFREQ:      0
  #   plot:
  #     - flow_lat            # Flow vs latency

# ----------------------------------------------------------------------------
# RPL/SDN
# ----------------------------------------------------------------------------
  # - desc:           RPL
  #   makeargs:
  #     MAC:          CONTIKIMAC
  #     SDN:          0
  #     NUM_APPS:     1
  #     APPID:        [1]
  #     TXNODES:      0
  #     RXNODES:      1
  #     BRMIN:        [60]
  #     BRMAX:        [75]
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_traffic_ratio   # SDN traffic ratio
  # - desc:           SDN
  #   makeargs:
  #     MAC:          CONTIKIMAC
  #     SDN:          1
  #     NUM_APPS:     1
  #     APPID:        [1]
  #     TXNODES:      0
  #     RXNODES:      1
  #     BRMIN:        [60]
  #     BRMAX:        [75]
  #     FTSRETRY:     0
  #     NSUFREQ:      0
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio
# ----------------------------------------------------------------------------
# NSU
# ----------------------------------------------------------------------------
  # - desc:           SDN-NSU-10
  #   makeargs:
  #     MAC:          NULLMAC
  #     SDN:          1
  #     NUM_APPS:     1
  #     APPID:        [1]
  #     TXNODES:      0
  #     RXNODES:      1
  #     BRMIN:        [60]
  #     BRMAX:        [75]
  #     FTSRETRY:     0
  #     NSUFREQ:      10
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio
  # - desc:           SDN-NSU-60
  #   makeargs:
  #     MAC:          NULLMAC
  #     SDN:          1
  #     NUM_APPS:     1
  #     APPID:        [1]
  #     TXNODES:      0
  #     RXNODES:      1
  #     BRMIN:        [60]
  #     BRMAX:        [75]
  #     FTSRETRY:     0
  #     NSUFREQ:      60
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio
  # - desc:           SDN-NSU-600
  #   makeargs:
  #     MAC:          NULLMAC
  #     SDN:          1
  #     NUM_APPS:     1
  #     APPID:        [1]
  #     TXNODES:      0
  #     RXNODES:      1
  #     BRMIN:        [60]
  #     BRMAX:        [75]
  #     FTSRETRY:     0
  #     NSUFREQ:      600
  #   plot:
  #     - hops_rdc            # Radio duty cycle vs hops
  #     - hops_prr            # Packet receive ratio vs hops
  #     - hops_lat_mean       # Hops vs mean latency
  #     - hops_lat_e2e        # Hops vs end-to-end latency
  #     - sdn_join            # SDN controller join time
  #     - sdn_traffic_ratio   # SDN traffic ratio

# ----------------------------------------------------------------------------
# FTS
# ----------------------------------------------------------------------------
  - desc:           SDN-FTS-60
    makeargs:
      MAC:          CONTIKIMAC
      SDN:          1
      NUM_APPS:     1
      APPID:        [1]
      TXNODES:      0
      RXNODES:      1
      BRMIN:        [10]
      BRMAX:        [15]
      FTSRETRY:     1
      FTREFRESH:    0
      FTSFREQ:      60
    plot:
      - hops_rdc            # Radio duty cycle vs hops
      - hops_prr            # Packet receive ratio vs hops
      - hops_lat_mean       # Hops vs mean latency
      - hops_lat_e2e        # Hops vs end-to-end latency
      - sdn_join            # SDN controller join time
      - sdn_traffic_ratio   # SDN traffic ratio
  - desc:           SDN-FTS-180
    makeargs:
      MAC:          CONTIKIMAC
      SDN:          1
      NUM_APPS:     1
      APPID:        [1]
      TXNODES:      0
      RXNODES:      1
      BRMIN:        [10]
      BRMAX:        [15]
      FTSRETRY:     1
      FTREFRESH:    0
      FTSFREQ:      180
    plot:
      - hops_rdc            # Radio duty cycle vs hops
      - hops_prr            # Packet receive ratio vs hops
      - hops_lat_mean       # Hops vs mean latency
      - hops_lat_e2e        # Hops vs end-to-end latency
      - sdn_join            # SDN controller join time
      - sdn_traffic_ratio   # SDN traffic ratio
  - desc:           SDN-FTS-240
    makeargs:
      MAC:          CONTIKIMAC
      SDN:          1
      NUM_APPS:     1
      APPID:        [1]
      TXNODES:      0
      RXNODES:      1
      BRMIN:        [10]
      BRMAX:        [15]
      FTSRETRY:     1
      FTREFRESH:    0
      FTSFREQ:      240
    plot:
      - hops_rdc            # Radio duty cycle vs hops
      - hops_prr            # Packet receive ratio vs hops
      - hops_lat_mean       # Hops vs mean latency
      - hops_lat_e2e        # Hops vs end-to-end latency
      - sdn_join            # SDN controller join time
      - sdn_traffic_ratio   # SDN traffic ratio

# ----------------------------------------------------------------------------
# analysis (comparison) config
# ----------------------------------------------------------------------------
analysis:
# ----------------------------------------------------------------------------
  # - sims:
  #   - SDN
  #   - RPL
  #   plots:
  #     - hops_rdc
  #     - hops_prr
  #     - hops_lat_mean
  #     - hops_lat_e2e
# ----------------------------------------------------------------------------
  #
  # - sims:
  #   - SDN
  #   plots:
  #   - join
# ----------------------------------------------------------------------------
  # - sims:
  #   - SDN-Scenario
  #   - RPL-Scenario
  #   plots:
  #     - flow_lat
# ----------------------------------------------------------------------------
  # - sims:
  #   - SDN-NSU-10
  #   - SDN-NSU-60
  #   - SDN-NSU-600
  #   plots:
  #     - hops_rdc
  #     - hops_prr
  #     - hops_lat_mean
  #     - hops_lat_e2e
# ----------------------------------------------------------------------------
  - sims:
    - SDN-FTS-60
    - SDN-FTS-180
    - SDN-FTS-240
    plots:
      - hops_rdc
      - hops_prr
      - hops_lat_mean
      - hops_lat_e2e
